version: "0.2"
ignorePaths: ["settings.toml"]
dictionaryDefinitions: []
dictionaries: []
words:
  - chrono
  - colour
  - dotenv
  - HMAC
  - reqwest
  - serde
  - Srgb
  - tuya
ignoreWords: []
import: []
